name: Setup NPM Packages
description: Setup required NPM packages

runs:
  using: composite
  steps:
  - name: Get pnpm store path
    id: pnpm-store
    run: bash scripts/setup-pnpm-cache.sh
    shell: bash

  - name: Cache pnpm store
    uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
    with:
      path: ${{ env.STORE_PATH }}
      key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      restore-keys: |
        pnpm-${{ runner.os }}-

  - name: Install packages
    run: bash scripts/install-node-packages.sh
    shell: bash
