name: Setup NPM Packages
description: Setup required NPM packages

runs:
  using: composite
  steps:
  - name: Get pnpm store path
    id: pnpm-store
    run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV
    shell: bash

  - name: Cache pnpm store
    uses: actions/cache@v5
    with:
      path: ${{ env.STORE_PATH }}
      key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      restore-keys: |
        pnpm-${{ runner.os }}-

  - name: Install packages
    run: pnpm install
    shell: bash
