name: Setup NPM Packages
description: Setup required NPM packages

runs:
  using: composite
  steps:
  - uses: actions/cache@7921ae235bdcb376cc8f22558dc5f8ddc3c3c2f9
    with:
      path: |
        ~/.local/share/pnpm/store/v3
      key: ${{ runner.os }}-pnpm-${{ hashFiles('**/.tool-versions') }}-${{ hashFiles('**/pnpm-lock.yaml') }}

  - name: Install packages
    run: |
      pnpm install
    shell: bash
