name: Setup NPM Packages
description: Setup required NPM packages

runs:
  using: composite
  steps:
  - uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb
    with:
      path: |
        ~/.local/share/pnpm/store/v3
      key: ${{ runner.os }}-pnpm-${{ hashFiles('**/.tool-versions') }}-${{ hashFiles('**/pnpm-lock.yaml') }}

  - name: Install packages
    run: |
      pnpm install
    shell: bash
