name: Setup NPM Packages
description: Setup required NPM packages

runs:
  using: composite
  steps:
  - uses: actions/cache@638ed79f9dc94c1de1baef91bcab5edaa19451f4
    with:
      path: |
        ~/.local/share/pnpm/store/v3
      key: ${{ runner.os }}-pnpm-${{ hashFiles('**/.tool-versions') }}-${{ hashFiles('**/pnpm-lock.yaml') }}

  - name: Install packages
    run: |
      pnpm install
    shell: bash
