name: Setup Tools
description: Setup required tools in the workspace

runs:
  using: composite
  steps:
  - name: Setup Tools
    uses: egose/actions/asdf-tools@1b63e8736d5fcf7005bd8887e121c3badd7659e7
    with:
      plugins: |
        mongodb=https://github.com/junminahn/asdf-mongodb.git

  - name: Install python tools
    run: |
      pip install -r requirements.txt
      asdf reshim
    shell: bash
