name: Setup Tools
description: Setup required tools in the workspace

runs:
  using: composite
  steps:
  - name: Setup Tools
    uses: egose/actions/asdf-tools@fb7c0ce76762ce2b5bc5d081efe23aed7dd854bb
    with:
      plugins: |
        mongodb=https://github.com/junminahn/asdf-mongodb.git

  - name: Install python tools
    run: |
      pip install -r requirements.txt
      asdf reshim
    shell: bash
