name: Setup Tools
description: Setup required tools in the workspace

runs:
  using: composite
  steps:
  - name: Setup Tools
    uses: egose/actions/asdf-tools@dbaf52744a94ea447277148274488bfcdf6b13a8
    with:
      plugins: |
        mongodb=https://github.com/junminahn/asdf-mongodb.git

  - name: Install python tools
    run: |
      pip install -r requirements.txt
      asdf reshim
    shell: bash
