name: Setup Tools
description: Setup required tools in the workspace

runs:
  using: composite
  steps:
  - name: Setup Tools
    uses: egose/actions/asdf-tools@31518a57045ca3610981d235de3c520e96cb9397
    with:
      plugins: |
        mongodb=https://github.com/junminahn/asdf-mongodb.git

  - name: Install python tools
    run: |
      pip install -r requirements.txt
      asdf reshim
    shell: bash
