import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  about: [{ type: 'autogenerated', dirName: 'about' }],
  operations: [{ type: 'autogenerated', dirName: 'operations' }],
  deployment: [{ type: 'autogenerated', dirName: 'deployment' }],
  reference: [{ type: 'autogenerated', dirName: 'reference' }],
};

export default sidebars;
