name: Setup NPM Packages
description: Setup required NPM packages

runs:
  using: composite
  steps:
  - uses: actions/cache@81382a721fc89d96eca335d0c3ba33144b2baa9d
    with:
      path: |
        **/node_modules
      key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

  - name: Install packages
    run: yarn
    shell: bash
