name: Setup NPM Packages
description: Setup required NPM packages

runs:
  using: composite
  steps:
  - uses: actions/cache@36f1e144e1c8edb0a652766b484448563d8baf46
    with:
      path: |
        **/node_modules
      key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

  - name: Install packages
    run: yarn
    shell: bash
