name: Setup NPM Packages
description: Setup required NPM packages

runs:
  using: composite
  steps:
  - uses: actions/cache@8469c94c6a180dfb41a1bd7e1b46ac557ea124f1
    with:
      path: |
        **/node_modules
      key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

  - name: Install packages
    run: yarn
    shell: bash
