name: Setup NPM Packages
description: Setup required NPM packages

runs:
  using: composite
  steps:
  - uses: actions/cache@9fa7e61ec7e1f44ac75218e7aaea81da8856fd11
    with:
      path: |
        **/node_modules
      key: ${{ runner.os }}-yarn-${{ hashFiles('**/.tool-versions') }}-${{ hashFiles('**/yarn.lock') }}

  - name: Install packages
    run: |
      yarn install --ignore-engines
    shell: bash
