name: Setup NPM Packages
description: Setup required NPM packages

runs:
  using: composite
  steps:
  - uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57
    with:
      path: |
        **/node_modules
      key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

  - name: Install packages
    run: yarn
    shell: bash
